/*
 * This file is generated by jOOQ.
 */
package com.musscraft.database.jOOQ;


import com.musscraft.database.jOOQ.tables.Mussplayer;
import com.musscraft.database.jOOQ.tables.Nexus;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>MussCraft</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index MUSSPLAYER_MUSSPLAYER_EMAIL_UINDEX = Indexes0.MUSSPLAYER_MUSSPLAYER_EMAIL_UINDEX;
    public static final Index MUSSPLAYER_MUSSPLAYER_UID_UINDEX = Indexes0.MUSSPLAYER_MUSSPLAYER_UID_UINDEX;
    public static final Index MUSSPLAYER_MUSSPLAYER_USERNAME_UINDEX = Indexes0.MUSSPLAYER_MUSSPLAYER_USERNAME_UINDEX;
    public static final Index MUSSPLAYER_PRIMARY = Indexes0.MUSSPLAYER_PRIMARY;
    public static final Index NEXUS_NEXUS_CREATORUID_UINDEX = Indexes0.NEXUS_NEXUS_CREATORUID_UINDEX;
    public static final Index NEXUS_NEXUS_NAME_UINDEX = Indexes0.NEXUS_NEXUS_NAME_UINDEX;
    public static final Index NEXUS_NEXUS_UID_UINDEX = Indexes0.NEXUS_NEXUS_UID_UINDEX;
    public static final Index NEXUS_PRIMARY = Indexes0.NEXUS_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index MUSSPLAYER_MUSSPLAYER_EMAIL_UINDEX = Internal.createIndex("MussPlayer_email_uindex", Mussplayer.MUSSPLAYER, new OrderField[] { Mussplayer.MUSSPLAYER.EMAIL }, true);
        public static Index MUSSPLAYER_MUSSPLAYER_UID_UINDEX = Internal.createIndex("MussPlayer_UID_uindex", Mussplayer.MUSSPLAYER, new OrderField[] { Mussplayer.MUSSPLAYER.UID }, true);
        public static Index MUSSPLAYER_MUSSPLAYER_USERNAME_UINDEX = Internal.createIndex("MussPlayer_username_uindex", Mussplayer.MUSSPLAYER, new OrderField[] { Mussplayer.MUSSPLAYER.USERNAME }, true);
        public static Index MUSSPLAYER_PRIMARY = Internal.createIndex("PRIMARY", Mussplayer.MUSSPLAYER, new OrderField[] { Mussplayer.MUSSPLAYER.UID }, true);
        public static Index NEXUS_NEXUS_CREATORUID_UINDEX = Internal.createIndex("Nexus_creatorUid_uindex", Nexus.NEXUS, new OrderField[] { Nexus.NEXUS.CREATORUID }, true);
        public static Index NEXUS_NEXUS_NAME_UINDEX = Internal.createIndex("Nexus_name_uindex", Nexus.NEXUS, new OrderField[] { Nexus.NEXUS.NAME }, true);
        public static Index NEXUS_NEXUS_UID_UINDEX = Internal.createIndex("Nexus_uid_uindex", Nexus.NEXUS, new OrderField[] { Nexus.NEXUS.UID }, true);
        public static Index NEXUS_PRIMARY = Internal.createIndex("PRIMARY", Nexus.NEXUS, new OrderField[] { Nexus.NEXUS.UID }, true);
    }
}
