/*
 * This file is generated by jOOQ.
 */
package com.musscraft.database.jOOQ;


import com.musscraft.database.jOOQ.tables.Mussplayer;
import com.musscraft.database.jOOQ.tables.records.MussplayerRecord;

import javax.annotation.Generated;

import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>MussCraft</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<MussplayerRecord> KEY_MUSSPLAYER_PRIMARY = UniqueKeys0.KEY_MUSSPLAYER_PRIMARY;
    public static final UniqueKey<MussplayerRecord> KEY_MUSSPLAYER_MUSSPLAYER_UID_UINDEX = UniqueKeys0.KEY_MUSSPLAYER_MUSSPLAYER_UID_UINDEX;
    public static final UniqueKey<MussplayerRecord> KEY_MUSSPLAYER_MUSSPLAYER_USERNAME_UINDEX = UniqueKeys0.KEY_MUSSPLAYER_MUSSPLAYER_USERNAME_UINDEX;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<MussplayerRecord> KEY_MUSSPLAYER_PRIMARY = Internal.createUniqueKey(Mussplayer.MUSSPLAYER, "KEY_MussPlayer_PRIMARY", Mussplayer.MUSSPLAYER.UID);
        public static final UniqueKey<MussplayerRecord> KEY_MUSSPLAYER_MUSSPLAYER_UID_UINDEX = Internal.createUniqueKey(Mussplayer.MUSSPLAYER, "KEY_MussPlayer_MussPlayer_UID_uindex", Mussplayer.MUSSPLAYER.UID);
        public static final UniqueKey<MussplayerRecord> KEY_MUSSPLAYER_MUSSPLAYER_USERNAME_UINDEX = Internal.createUniqueKey(Mussplayer.MUSSPLAYER, "KEY_MussPlayer_MussPlayer_username_uindex", Mussplayer.MUSSPLAYER.USERNAME);
    }
}
