/*
 * This file is generated by jOOQ.
 */
package com.musscraft.database.jOOQ;


import com.musscraft.database.jOOQ.tables.Mussplayer;
import com.musscraft.database.jOOQ.tables.Nexus;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Musscraft extends SchemaImpl {

    private static final long serialVersionUID = -1562723071;

    /**
     * The reference instance of <code>MussCraft</code>
     */
    public static final Musscraft MUSSCRAFT = new Musscraft();

    /**
     * The table <code>MussCraft.MussPlayer</code>.
     */
    public final Mussplayer MUSSPLAYER = com.musscraft.database.jOOQ.tables.Mussplayer.MUSSPLAYER;

    /**
     * The table <code>MussCraft.Nexus</code>.
     */
    public final Nexus NEXUS = com.musscraft.database.jOOQ.tables.Nexus.NEXUS;

    /**
     * No further instances allowed
     */
    private Musscraft() {
        super("MussCraft", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Mussplayer.MUSSPLAYER,
            Nexus.NEXUS);
    }
}
