/*
 * This file is generated by jOOQ.
 */
package com.musscraft.database.jOOQ;


import com.musscraft.database.jOOQ.tables.Mussplayer;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in MussCraft
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>MussCraft.MussPlayer</code>.
     */
    public static final Mussplayer MUSSPLAYER = com.musscraft.database.jOOQ.tables.Mussplayer.MUSSPLAYER;
}
