/*
 * This file is generated by jOOQ.
 */
package com.musscraft.database.jOOQ.tables.records;


import com.musscraft.database.jOOQ.tables.Mussplayer;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record8;
import org.jooq.Row8;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MussplayerRecord extends UpdatableRecordImpl<MussplayerRecord> implements Record8<String, String, String, String, Double, Double, String, Byte> {

    private static final long serialVersionUID = -823771901;

    /**
     * Setter for <code>MussCraft.MussPlayer.UID</code>.
     */
    public void setUid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>MussCraft.MussPlayer.UID</code>.
     */
    public String getUid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>MussCraft.MussPlayer.username</code>.
     */
    public void setUsername(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MussCraft.MussPlayer.username</code>.
     */
    public String getUsername() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MussCraft.MussPlayer.password</code>.
     */
    public void setPassword(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>MussCraft.MussPlayer.password</code>.
     */
    public String getPassword() {
        return (String) get(2);
    }

    /**
     * Setter for <code>MussCraft.MussPlayer.email</code>.
     */
    public void setEmail(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>MussCraft.MussPlayer.email</code>.
     */
    public String getEmail() {
        return (String) get(3);
    }

    /**
     * Setter for <code>MussCraft.MussPlayer.money</code>.
     */
    public void setMoney(Double value) {
        set(4, value);
    }

    /**
     * Getter for <code>MussCraft.MussPlayer.money</code>.
     */
    public Double getMoney() {
        return (Double) get(4);
    }

    /**
     * Setter for <code>MussCraft.MussPlayer.experience</code>.
     */
    public void setExperience(Double value) {
        set(5, value);
    }

    /**
     * Getter for <code>MussCraft.MussPlayer.experience</code>.
     */
    public Double getExperience() {
        return (Double) get(5);
    }

    /**
     * Setter for <code>MussCraft.MussPlayer.location</code>.
     */
    public void setLocation(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>MussCraft.MussPlayer.location</code>.
     */
    public String getLocation() {
        return (String) get(6);
    }

    /**
     * Setter for <code>MussCraft.MussPlayer.logged</code>.
     */
    public void setLogged(Byte value) {
        set(7, value);
    }

    /**
     * Getter for <code>MussCraft.MussPlayer.logged</code>.
     */
    public Byte getLogged() {
        return (Byte) get(7);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record8 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, Double, Double, String, Byte> fieldsRow() {
        return (Row8) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row8<String, String, String, String, Double, Double, String, Byte> valuesRow() {
        return (Row8) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Mussplayer.MUSSPLAYER.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Mussplayer.MUSSPLAYER.USERNAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Mussplayer.MUSSPLAYER.PASSWORD;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Mussplayer.MUSSPLAYER.EMAIL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field5() {
        return Mussplayer.MUSSPLAYER.MONEY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field6() {
        return Mussplayer.MUSSPLAYER.EXPERIENCE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Mussplayer.MUSSPLAYER.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field8() {
        return Mussplayer.MUSSPLAYER.LOGGED;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component5() {
        return getMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component6() {
        return getExperience();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component8() {
        return getLogged();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getUsername();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPassword();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getEmail();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value5() {
        return getMoney();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value6() {
        return getExperience();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value8() {
        return getLogged();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MussplayerRecord value1(String value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MussplayerRecord value2(String value) {
        setUsername(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MussplayerRecord value3(String value) {
        setPassword(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MussplayerRecord value4(String value) {
        setEmail(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MussplayerRecord value5(Double value) {
        setMoney(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MussplayerRecord value6(Double value) {
        setExperience(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MussplayerRecord value7(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MussplayerRecord value8(Byte value) {
        setLogged(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public MussplayerRecord values(String value1, String value2, String value3, String value4, Double value5, Double value6, String value7, Byte value8) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached MussplayerRecord
     */
    public MussplayerRecord() {
        super(Mussplayer.MUSSPLAYER);
    }

    /**
     * Create a detached, initialised MussplayerRecord
     */
    public MussplayerRecord(String uid, String username, String password, String email, Double money, Double experience, String location, Byte logged) {
        super(Mussplayer.MUSSPLAYER);

        set(0, uid);
        set(1, username);
        set(2, password);
        set(3, email);
        set(4, money);
        set(5, experience);
        set(6, location);
        set(7, logged);
    }
}
