/*
 * This file is generated by jOOQ.
 */
package com.musscraft.database.jOOQ.tables.records;


import com.musscraft.database.jOOQ.tables.Nexus;

import java.sql.Date;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.11.11"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class NexusRecord extends UpdatableRecordImpl<NexusRecord> implements Record7<String, String, Double, Integer, Date, String, String> {

    private static final long serialVersionUID = -1020781271;

    /**
     * Setter for <code>MussCraft.Nexus.uid</code>.
     */
    public void setUid(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>MussCraft.Nexus.uid</code>.
     */
    public String getUid() {
        return (String) get(0);
    }

    /**
     * Setter for <code>MussCraft.Nexus.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>MussCraft.Nexus.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>MussCraft.Nexus.health</code>.
     */
    public void setHealth(Double value) {
        set(2, value);
    }

    /**
     * Getter for <code>MussCraft.Nexus.health</code>.
     */
    public Double getHealth() {
        return (Double) get(2);
    }

    /**
     * Setter for <code>MussCraft.Nexus.power</code>.
     */
    public void setPower(Integer value) {
        set(3, value);
    }

    /**
     * Getter for <code>MussCraft.Nexus.power</code>.
     */
    public Integer getPower() {
        return (Integer) get(3);
    }

    /**
     * Setter for <code>MussCraft.Nexus.destroyedDate</code>.
     */
    public void setDestroyeddate(Date value) {
        set(4, value);
    }

    /**
     * Getter for <code>MussCraft.Nexus.destroyedDate</code>.
     */
    public Date getDestroyeddate() {
        return (Date) get(4);
    }

    /**
     * Setter for <code>MussCraft.Nexus.location</code>.
     */
    public void setLocation(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>MussCraft.Nexus.location</code>.
     */
    public String getLocation() {
        return (String) get(5);
    }

    /**
     * Setter for <code>MussCraft.Nexus.creatorUid</code>.
     */
    public void setCreatoruid(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>MussCraft.Nexus.creatorUid</code>.
     */
    public String getCreatoruid() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Double, Integer, Date, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<String, String, Double, Integer, Date, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Nexus.NEXUS.UID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Nexus.NEXUS.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Double> field3() {
        return Nexus.NEXUS.HEALTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field4() {
        return Nexus.NEXUS.POWER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Date> field5() {
        return Nexus.NEXUS.DESTROYEDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Nexus.NEXUS.LOCATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Nexus.NEXUS.CREATORUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double component3() {
        return getHealth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component4() {
        return getPower();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date component5() {
        return getDestroyeddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCreatoruid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getUid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Double value3() {
        return getHealth();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value4() {
        return getPower();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Date value5() {
        return getDestroyeddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getLocation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCreatoruid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NexusRecord value1(String value) {
        setUid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NexusRecord value2(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NexusRecord value3(Double value) {
        setHealth(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NexusRecord value4(Integer value) {
        setPower(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NexusRecord value5(Date value) {
        setDestroyeddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NexusRecord value6(String value) {
        setLocation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NexusRecord value7(String value) {
        setCreatoruid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public NexusRecord values(String value1, String value2, Double value3, Integer value4, Date value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached NexusRecord
     */
    public NexusRecord() {
        super(Nexus.NEXUS);
    }

    /**
     * Create a detached, initialised NexusRecord
     */
    public NexusRecord(String uid, String name, Double health, Integer power, Date destroyeddate, String location, String creatoruid) {
        super(Nexus.NEXUS);

        set(0, uid);
        set(1, name);
        set(2, health);
        set(3, power);
        set(4, destroyeddate);
        set(5, location);
        set(6, creatoruid);
    }
}
